version: '3'

services:

  mysql:
   image: mysql:latest
   ports:
    - "3307:3306"
   environment:
    MYSQL_ROOT_PASSWORD: root
   volumes:
      - airplane_bookung_mysql-data:/var/lib/mysql

  airplane:
    build: 
      dockerfile: Dockerfile
      context: ./airplane
    container_name: airplane
    ports:
      - "4001:4001"
    restart: always
    env_file:
      - ./airplane/.env
    depends_on:
      - rabbtimq
      - mysql

  apigatewaya:
    build: 
      dockerfile: Dockerfile
      context: ./apigatewaya
    container_name: apigatewaya
    ports:
      - "4000:4000"
    restart: always
    env_file:
      - ./apigatewaya/.env
    depends_on:
      - rabbtimq
      - airplane
      - booking
      - notification
      - user
      - mysql

  booking:
    build: 
      dockerfile: Dockerfile
      context: ./booking
    container_name: booking
    ports:
      - "4002:4002"
    restart: always
    env_file:
      - ./booking/.env
    depends_on:
      - rabbtimq
      - mysql

  notification:
    build: 
      dockerfile: Dockerfile
      context: ./notification
    container_name: notification
    ports:
      - "4003:4003"
    restart: always
    env_file:
      - ./notification/.env
    depends_on:
      rabbtimq:
        condition: service_healthy

  user:
    build: 
      dockerfile: Dockerfile
      context: ./user
    container_name: user
    ports:
      - "4004:4004"
    restart: always
    env_file:
      - ./user/.env
    depends_on:
      - rabbtimq
      - mysql

  client:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    container_name: client
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - apigatewaya

  rabbtimq:
    image: rabbitmq:4-management
    container_name: rabbtimq
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  airplane_bookung_mysql-data: 